# Generated by Django 5.2.14 on 2026-05-22 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('title_hi', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('description_hi', models.TextField()),
                ('icon', models.CharField(choices=[('leaf', 'Leaf / Organic'), ('quality', 'Quality check'), ('visit', 'Visit shop')], default='leaf', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CropSeedRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('name_hi', models.CharField(max_length=128)),
                ('kg_per_acre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg/acre', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('question_hi', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('answer_hi', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FarmingTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_hi', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('excerpt_hi', models.TextField()),
                ('content', models.TextField()),
                ('content_hi', models.TextField()),
                ('season', models.CharField(max_length=64)),
                ('season_hi', models.CharField(max_length=64)),
                ('icon', models.CharField(blank=True, max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_hi', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description_hi', models.TextField()),
                ('benefit', models.TextField()),
                ('benefit_hi', models.TextField()),
                ('link', models.URLField(max_length=500)),
                ('icon', models.CharField(blank=True, max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Government scheme',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_hi', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('seeds', 'Seeds'), ('fertilizer', 'Fertilizers'), ('pesticides', 'Pesticides'), ('tools', 'Farming Tools'), ('organic', 'Organic Products'), ('animal_feed', 'Animal Feed'), ('irrigation', 'Irrigation')], max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('description_hi', models.TextField()),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('coming_soon', 'Coming Soon')], default='in_stock', max_length=20)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicePincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(db_index=True, max_length=6, unique=True)),
            ],
            options={
                'ordering': ['pincode'],
            },
        ),
        migrations.CreateModel(
            name='ShopGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('caption', models.CharField(max_length=255)),
                ('caption_hi', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shop gallery image',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(default='918318576674', max_length=20)),
                ('phone_display', models.CharField(default='+91 8318576674', max_length=32)),
                ('email', models.EmailField(default='info@agroseeds.com', max_length=254)),
                ('address', models.TextField(default='123 Agriculture Market, Delhi - 110001, India')),
                ('maps_url', models.URLField(blank=True, max_length=500)),
                ('maps_embed_url', models.URLField(blank=True, max_length=1000)),
                ('metro_note', models.CharField(blank=True, max_length=255)),
                ('metro_note_hi', models.CharField(blank=True, max_length=255)),
                ('bus_note', models.CharField(blank=True, max_length=255)),
                ('bus_note_hi', models.CharField(blank=True, max_length=255)),
                ('parking_note', models.CharField(blank=True, max_length=255)),
                ('parking_note_hi', models.CharField(blank=True, max_length=255)),
                ('contact_note', models.TextField(blank=True)),
                ('contact_note_hi', models.TextField(blank=True)),
                ('weekday_label', models.CharField(default='Monday - Saturday', max_length=64)),
                ('weekday_label_hi', models.CharField(default='सोमवार - शनिवार', max_length=64)),
                ('sunday_label', models.CharField(default='Sunday', max_length=64)),
                ('sunday_label_hi', models.CharField(default='रविवार', max_length=64)),
                ('weekday_hours', models.CharField(default='9:00 AM - 7:00 PM', max_length=32)),
                ('sunday_hours', models.CharField(default='10:00 AM - 5:00 PM', max_length=32)),
                ('weekday_open_hour', models.PositiveSmallIntegerField(default=9)),
                ('weekday_close_hour', models.PositiveSmallIntegerField(default=19)),
                ('sunday_open_hour', models.PositiveSmallIntegerField(default=10)),
                ('sunday_close_hour', models.PositiveSmallIntegerField(default=17)),
                ('stat_years', models.CharField(default='15+', max_length=16)),
                ('stat_farmers', models.CharField(default='5000+', max_length=16)),
                ('stat_products', models.CharField(default='20+', max_length=16)),
                ('stat_quality', models.CharField(default='100%', max_length=16)),
            ],
            options={
                'verbose_name': 'Shop settings',
                'verbose_name_plural': 'Shop settings',
            },
        ),
        migrations.CreateModel(
            name='SowingCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_label', models.CharField(max_length=64)),
                ('month_label_hi', models.CharField(max_length=64)),
                ('season', models.CharField(max_length=64)),
                ('season_hi', models.CharField(max_length=64)),
                ('crops_en', models.JSONField(default=list, help_text='["Wheat", "Mustard"]')),
                ('crops_hi', models.JSONField(default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sowing calendar entry',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_hi', models.CharField(blank=True, max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('location_hi', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField()),
                ('text_hi', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('crop', models.CharField(help_text='Farming type e.g. Wheat Farmer', max_length=128)),
                ('crop_hi', models.CharField(blank=True, max_length=128)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('farming_type', models.CharField(max_length=128)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('description', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropAdvisorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('kharif', 'Kharif (Monsoon)'), ('rabi', 'Rabi (Winter)'), ('zaid', 'Zaid (Summer)')], max_length=16)),
                ('goal', models.CharField(choices=[('vegetables', 'Vegetables'), ('grains', 'Grains'), ('organic', 'Organic farming')], max_length=16)),
                ('recommended_category', models.CharField(choices=[('seeds', 'Seeds'), ('fertilizer', 'Fertilizers'), ('pesticides', 'Pesticides'), ('tools', 'Farming Tools'), ('organic', 'Organic Products'), ('animal_feed', 'Animal Feed'), ('irrigation', 'Irrigation')], max_length=32)),
            ],
            options={
                'verbose_name': 'Crop advisor rule',
                'unique_together': {('season', 'goal')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/extra/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='shop.product')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
