# Generated by Django 5.2.14 on 2026-05-22 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialsuggestion',
            name='published_testimonial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_suggestion', to='shop.testimonial'),
        ),
    ]
